import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import bootstrap from 'bootstrap/dist/css/bootstrap.min.css';
import { ThemeProvider } from '@/context/theme';
import TopNav from '@/components/nav/TopNav';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Multi User Blog',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <TopNav />
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
